name: Continuous integration

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  check-style:
    name: Check style
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: --all-targets

  check-docs:
    name: Check rustdoc
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Check rustdoc
        run: RUSTDOCFLAGS="--cfg docsrs --deny rustdoc::broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items --all-features

  check-code:
    name: Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-hack
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-hack
          version: 0.5

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Cargo check all targets and features
        run: cargo hack check --workspace --each-feature --all-targets

  tests_ubuntu:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staking-miner sources
        uses: actions/checkout@v3

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Show working directory
        run: ls

      - name: Cargo test
        run: RUST_LOG=info cargo test --workspace -- --nocapture
